approvedGitRepositories:
  - "https://github.com/lipemat/*"

enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0004
    level: discard

nodeLinker: pnp

npmMinimalAgeGate: 1w

npmPreapprovedPackages:
  - "@lipemat/*"

pnpEnableEsmLoader: true

pnpFallbackMode: all

pnpMode: loose

supportedArchitectures:
  os:
    - current
    - linux
