enableGlobalCache: false
enableScripts: false
nodeLinker: pnp
# JEST requires ESM to be enabled for .ts config files.
pnpEnableEsmLoader: true
pnpFallbackMode: all
pnpMode: loose

supportedArchitectures:
  os:
    - "current"
    - "linux"

logFilters:
  # Disable the warnings when peer dependencies are not provided due to boilerplate.
  - code: YN0002
    level: discard
  # Disable warning of third party build scripts we don't let run.
  - code: YN0004
    level: discard
