<?php

declare( strict_types=1 );

namespace Lipe\Lib\Query\Clause;

/**
 * Shared properties and methods for working with `date_query`.
 *
 * @since 4.0.0
 */
trait Date_Query_Trait {
	/**
	 * Meta query generated by `date_query()`.
	 *
	 * @internal
	 *
	 * @see Args::date_query()
	 *
	 * @var array
	 */
	public array $date_query;


	/**
	 * Generate the `date_query` clauses.
	 *
	 * @link https://developer.wordpress.org/reference/classes/wp_query/#date-parameters
	 *
	 * @return Date_Query
	 */
	public function date_query() : Date_Query {
		$query = new Date_Query();
		$this->clauses[] = $query;
		return $query;
	}
}
