#!/bin/sh
#
# Generate a .revision file to be used with browser cache busting
# @see /src/Theme/Styles.php
# For use when busting cache locally or when a Beanstalk deployment is not possible

git rev-parse HEAD > .revision
