#!/bin/bash

#####################################################################################
#
# Generate a .revision file to be used with browser cache busting locally.
#
# @see Resource::get_version
#
# @version 1.2.0
#
#####################################################################################

git rev-parse HEAD > .revision
