// Autogenerated by typings-for-css-modules-loader.
declare namespace RadioPcssNamespace {
	export interface IRadioPcss {
		control: string;
	}
}

declare const RadioPcssModule: RadioPcssNamespace.IRadioPcss;

export = RadioPcssModule;
