// Autogenerated by typings-for-css-modules-loader.
declare namespace SimplePcssNamespace {
	export interface ISimplePcss {
		control: string;
		none: string;
	}
}

declare const SimplePcssModule: SimplePcssNamespace.ISimplePcss;

export = SimplePcssModule;
