###################################################
# Create a GitHub Release when a tag is pushed.
#
# @notice You must enable write permissions for this action to work.
#   1. GitHub Settings
#   2. Actions
#   3. General
#   4. Workflow permissions
#   5. Enable "read and write permissions"
#
# @notice Need to add the `COPILOT_GITHUB_TOKEN` secret to the repository.
#   1. `gh secret set COPILOT_GITHUB_TOKEN --repo lipemat/wordpress-libs`
#   2. https://github.com/settings/personal-access-tokens/18009380
#      - Get value from vault.
#
# @version 5.0.0
#
###################################################

name: Create GitHub Release
run-name: Create release for ${{ github.ref_name }} on GitHub.

permissions:
  contents: write

on:
  push:
    tags-ignore:
      - "*beta*"

jobs:
  create-release:
    uses: lipemat/public-actions/.github/workflows/create-release.yml@version/2
    secrets: inherit
